"""Updated Booking model with booking_instance_id as primary key and added booking_id

Revision ID: 2d08ca7f0799
Revises: e04c032c7bb4
Create Date: 2024-08-14 14:04:09.659232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d08ca7f0799'
down_revision = 'e04c032c7bb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booking_instance_id', sa.Integer(), nullable=False, primary_key=True, autoincrement=True))
        batch_op.add_column(sa.Column('booking_id', sa.Integer(), nullable=False))
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.drop_column('booking_id')
        batch_op.drop_column('booking_instance_id')

    # ### end Alembic commands ###
