"""Add new schedule, daily account, expenses, and salaries models

Revision ID: 59d52ea97e7b
Revises: b5d773a1f94e
Create Date: 2024-07-28 13:06:47.506157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59d52ea97e7b'
down_revision = 'b5d773a1f94e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('day', sa.String(length=20), nullable=False),
    sa.Column('total_earnings_petrol', sa.Float(), nullable=False),
    sa.Column('daily_total_wage', sa.Float(), nullable=False),
    sa.Column('tj_earnings_per_day', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('salary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('day', sa.String(length=20), nullable=False),
    sa.Column('advance', sa.Float(), nullable=False),
    sa.Column('incentive', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['worker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('day', sa.String(length=20), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('pv', sa.Integer(), nullable=False),
    sa.Column('payment', sa.Float(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('time', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['worker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule')
    op.drop_table('salary')
    op.drop_table('expense')
    op.drop_table('daily_account')
    # ### end Alembic commands ###
