"""Remove booking_instance_id column from bookingModel

Revision ID: 67dec625f9c9
Revises: 2d08ca7f0799
Create Date: 2024-08-14 17:39:27.818720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67dec625f9c9'
down_revision = '2d08ca7f0799'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('booking_instance_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booking_instance_id', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
