"""Add area field to Worker model

Revision ID: 76d35ef63f0f
Revises: d0fd13b2ad42
Create Date: 2024-07-14 22:42:39.194426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76d35ef63f0f'
down_revision = 'd0fd13b2ad42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('area', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker', schema=None) as batch_op:
        batch_op.drop_column('area')

    # ### end Alembic commands ###
