"""Removed subscription fields from Client model

Revision ID: ad87a37b6a59
Revises: 59d52ea97e7b
Create Date: 2024-08-10 02:41:28.461854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad87a37b6a59'
down_revision = '59d52ea97e7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule')
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_column('subscription_start')
        batch_op.drop_column('subscription_end')
        batch_op.drop_column('subscription_plan')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_plan', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('subscription_end', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('subscription_start', sa.DATE(), nullable=True))

    op.create_table('schedule',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('day', sa.VARCHAR(length=20), nullable=False),
    sa.Column('client_id', sa.INTEGER(), nullable=False),
    sa.Column('pv', sa.INTEGER(), nullable=False),
    sa.Column('payment', sa.FLOAT(), nullable=False),
    sa.Column('worker_id', sa.INTEGER(), nullable=False),
    sa.Column('time', sa.VARCHAR(length=20), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['worker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
