"""Add area field to Client model

Revision ID: d0fd13b2ad42
Revises: d095ca6d67e9
Create Date: 2024-07-14 22:16:12.904499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0fd13b2ad42'
down_revision = 'd095ca6d67e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('area', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_column('area')

    # ### end Alembic commands ###
