"""Add recurrence_period to Booking model

Revision ID: e04c032c7bb4
Revises: ad87a37b6a59
Create Date: 2024-08-10 02:51:16.951266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e04c032c7bb4'
down_revision = 'ad87a37b6a59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recurrence_period', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('recurrence_period')

    # ### end Alembic commands ###
